import {useState} from 'react'
import {useLiveQuery} from 'dexie-react-hooks'
import {Download,HardDriveUpload,FileSpreadsheet,ShieldCheck,Trash2} from 'lucide-react'
import {SyncAccountCard} from '../components/SyncAccountCard'
import db,{downloadBackup,downloadRecordsCsv,restoreBackup} from '../db'
import {deleteSyncedStaff,notifyLocalChange} from '../sync'
import type {StaffRole} from '../types'

const defaultExercises=['ストレッチ','歩行練習','筋力トレーニング','バランス運動','自転車']
const defaultMinutes=['10分未満','10〜20分','20〜30分','30分以上']

export function DataPage(){
  const[message,setMessage]=useState('データは端末へ保存し、ログイン中はSupabaseとも同期されます。'),[busy,setBusy]=useState(false)
  const staff=useLiveQuery(()=>db.staff.toArray(),[])??[]
  const options=useLiveQuery(()=>db.recordOptions.get('record-options'),[])
  const backup=async()=>{setBusy(true);try{await downloadBackup();setMessage('JSONバックアップを保存しました。')}finally{setBusy(false)}}
  const restore=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);try{await restoreBackup(JSON.parse(await f.text()));notifyLocalChange(0);setMessage('復元しました。ログイン中の場合はSupabaseとも同期します。')}catch{setMessage('復元できませんでした。コンパスウォークのJSONファイルか確認してください。')}finally{setBusy(false);e.target.value=''}}
  const addStaff=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')??'').trim(),role=String(f.get('role')??'その他')as StaffRole;if(!name)return;const now=new Date().toISOString();await db.staff.add({name,role,createdAt:now,updatedAt:now});notifyLocalChange();e.currentTarget.reset();setMessage('担当者を追加しました。')}
  const addOption=async(kind:'exercises'|'exerciseMinutes',e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),value=String(f.get(kind)??'').trim(),current=options?.[kind]??(kind==='exercises'?defaultExercises:defaultMinutes);if(!value||current.includes(value))return;await db.recordOptions.put({id:'record-options',exercises:options?.exercises??defaultExercises,exerciseMinutes:options?.exerciseMinutes??defaultMinutes,[kind]:[...current,value],updatedAt:new Date().toISOString()});notifyLocalChange();e.currentTarget.reset();setMessage('選択肢を追加しました。')}
  const removeOption=async(kind:'exercises'|'exerciseMinutes',value:string)=>{const current=options?.[kind]??(kind==='exercises'?defaultExercises:defaultMinutes);await db.recordOptions.put({id:'record-options',exercises:options?.exercises??defaultExercises,exerciseMinutes:options?.exerciseMinutes??defaultMinutes,[kind]:current.filter(x=>x!==value),updatedAt:new Date().toISOString()});notifyLocalChange();setMessage('選択肢を削除しました。')}
  return <section className="data-page"><small>SETTINGS &amp; DATA</small><h1>設定・データ管理</h1><p>担当者、記録の選択肢、端末間同期を管理できます。</p><SyncAccountCard/><section className="data-card"><h2>担当者</h2><form className="manager-form" onSubmit={addStaff}><input name="name" placeholder="氏名" required/><select name="role" defaultValue="理学療法士"><option>理学療法士</option><option>柔道整復師</option><option>看護師</option><option>その他</option></select><button type="submit">追加</button></form><div className="manager-list">{staff.map(x=><span key={x.id}>{x.name}（{x.role}）<button type="button" aria-label={`${x.name}を削除`} onClick={()=>void deleteSyncedStaff(x.id!)}><Trash2 size={15}/></button></span>)}</div></section><section className="data-card"><h2>実施運動</h2><OptionManager name="exercises" placeholder="例：階段昇降" values={options?.exercises??defaultExercises} onAdd={addOption} onRemove={removeOption}/></section><section className="data-card"><h2>運動時間</h2><OptionManager name="exerciseMinutes" placeholder="例：30〜40分" values={options?.exerciseMinutes??defaultMinutes} onAdd={addOption} onRemove={removeOption}/></section><section className="safety-note"><ShieldCheck/><div><b>バックアップも併用してください</b><span>同期中でも、定期的なJSONバックアップをおすすめします。</span></div></section><section className="data-card"><h2>JSONバックアップ</h2><p>予定、記録、担当者、下書きをまとめて保存します。</p><button className="data-action" onClick={()=>void backup()} disabled={busy}><Download/>バックアップを保存</button></section><section className="data-card"><h2>JSON復元</h2><p>以前保存したバックアップを選択します。現在の端末データは置き換わります。</p><label className="data-action upload-action"><HardDriveUpload/>バックアップを復元<input type="file" accept="application/json,.json" onChange={restore} disabled={busy}/></label></section><section className="data-card"><h2>CSV出力</h2><p>記録を表計算ソフトで確認できるCSV形式で出力します。</p><button className="data-action" onClick={()=>void downloadRecordsCsv()}><FileSpreadsheet/>記録をCSV出力</button></section><p className="data-message" role="status">{message}</p></section>
}

function OptionManager({name,placeholder,values,onAdd,onRemove}:{name:'exercises'|'exerciseMinutes';placeholder:string;values:string[];onAdd:(kind:'exercises'|'exerciseMinutes',e:React.FormEvent<HTMLFormElement>)=>Promise<void>;onRemove:(kind:'exercises'|'exerciseMinutes',value:string)=>Promise<void>}){return <><form className="manager-form" onSubmit={e=>void onAdd(name,e)}><input name={name} placeholder={placeholder} required/><button type="submit">追加</button></form><div className="manager-list">{values.map(value=><span key={value}>{value}<button type="button" aria-label={`${value}を削除`} onClick={()=>void onRemove(name,value)}><Trash2 size={15}/></button></span>)}</div></>}
